export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_START = 'FETCH_STORIES_START';
export const FETCH_STORIES_FAIL = 'FETCH_STORIES_FAIL';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';

export const FETCH_START = 'FETCH_START';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';